Tca 21.04 (#4)
* Ubuntu as default OS, centos dropped from preconfig.
* add uefi/ovmf packages
* enable uefi boot by default for new VMs
* use ubunutu legacy iso for ubuntu20.04
* doc updates for ubuntu image issues

diff --git a/bin/kvmsh b/bin/kvmsh
--- a/bin/kvmsh
+++ b/bin/kvmsh
@@ -9,32 +9,33 @@
 #
 PNAME=${0##*\/}
 AUTHOR="tcarland@gmail.com"
-VERSION="v21.03"
+VERSION="v21.04"
 
 # ------------------------------------
 # defaults
-ubuntu="ubuntu20.04"
-focal="http://us.archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/"
-centos="centos7.0"
-centos7="CentOS-7-x86_64-Minimal-2003.iso"
+ubuntu="ubuntu20.04"  # default os-var
+focal="ubuntu-20.04.1-legacy-server-amd64.iso"  # default image
+# alternate web installer
+#focal="http://us.archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/"
 
 pool="default"
-network="bridge=br0"  # bridge=virbr0 is the default NAT interface
+network="bridge=br0"  # bridge=virbr0 is the KVM default local NAT interface
 ostype="linux"
-osvar="$ubuntu"
-image="$focal"
+osvar=
+image=
 
 memory="1024,maxmemory=2048"
 vcpus="1"
 graphics="vnc"
 use_console=1
+format="raw"  # or qcow2
 bootsz="40G"
 disksz="100G"
 mindisksz=5
 disknum=0
 dryrun=1
 cdrom=1
-format="raw"  # or qcow2
+uefi=0
 
 virt_uri="qemu:///system"
 virsh="virsh --connect $virt_uri"
@@ -80,9 +81,10 @@ Options:
   -N|--network  <if>      : KVM Network, default is '$network'.
   -m|--memory   <Mib>     : Memory allocation in Mb and optionally max memory.
                             eg. '--memory 1024' or '--memory $memory' 
-  -o|--os <ostype>        : Set virsh 'osvariant' for create. Default=$osvar 
+  -o|--os   <os-variant>  : Set virsh 'os-variant' for create. Default=$ubuntu 
   -p|--pool    <name>     : Storage pool to use, if not '$pool'.
   -u|--uri     <uri>      : Set the KVM connect uri. Default is '$virt_uri'.
+  -U|--no-uefi            : Disable UEFI boot support, enabled by default.
   -V|--version            : Show version info and exit. 
 
    <action>               : VM operation to perform, see below. 
@@ -133,7 +135,7 @@ list_all_pools()
 }
 
 
-is_running()
+vm_is_running()
 {
     local vm="$1"
     state=$( $virsh list | grep $vm | awk '{ print $3 }' )
@@ -313,13 +315,6 @@ while [ $# -gt 0 ]; do
             ;;
         -o|--os|--osvar*)
             osvar="$2"
-            if [ -z "$image" ]; then
-                if [[ $osvar =~ ubuntu ]]; then
-                    image="$focal"
-                elif [[ $osvar =~ centos ]]; then
-                    image="$centos7"
-                fi
-            fi
             shift
             ;;
         -p|--pool)
@@ -329,6 +324,9 @@ while [ $# -gt 0 ]; do
         -u|--uri)
             virt_uri="$2"
             shift
+            ;;
+        -U|--no-uefi|nouefi|no-efi|noefi)
+            uefi=1
             ;;
         'version'|-V|--version)
             echo "$version"
@@ -375,7 +373,7 @@ attach*)
         exit 1
     fi
 
-    if is_running $name; then
+    if vm_is_running $name; then
         live="--live"
     fi
 
@@ -419,6 +417,21 @@ create)
         exit 1
     fi
 
+    if [ -z "$image" ]; then
+        image="$focal"
+        osvar="$ubuntu"
+    elif [ -z "$osvar" ]; then
+        echo "$PNAME error: image provided but not os-variant, --osvar is required."
+        echo "  The tool 'osinfo-query os' will list os-variants."
+        exit 1
+    fi
+
+    if [[ $image =~ ^http ]]; then
+        srcimg="$image"
+    else
+        srcimg="$target/$image"
+    fi
+
     disk="$name-vda.img"
     diskimg="${target}/$disk"
 
@@ -430,25 +443,17 @@ create)
         exit $rt
     fi
 
-    if [[ $image =~ ^http ]]; then
-        srcimg="$image"
-    else
-        srcimg="$target/$image"
-    fi
-
-    if [ -z "$osvar" ]; then 
-        if [[ $srcimg =~ ubuntu ]]; then
-            osvar="$ubuntu"
-        elif [[ $srcimg =~ centos ]]; then
-            osvar="$centos"
-        fi
-    fi
-
     cmdargs=(--name "$name" \
-      --memory $memory --vcpus $vcpus \
-      --os-type "$ostype" --os-variant "$osvar" \
-      --disk "path=$diskimg" --network "$network")
+      --memory $memory \
+      --vcpus $vcpus \
+      --os-type "$ostype" \
+      --os-variant "$osvar" \
+      --disk "path=$diskimg" \
+      --network "$network")
 
+    if [ $uefi -eq 0 ]; then
+        cmdargs+=(--boot "uefi")
+    fi
     if [ $cdrom -eq 0 ]; then
         cmdargs+=(--cdrom "$srcimg")
     else
@@ -456,13 +461,18 @@ create)
     fi
 
     if [ $use_console -eq 0 ]; then
-        cmdargs+=(--graphics "none" --extra-args="$serial")
+        cmdargs+=(--graphics "none")
+        if [ $cdrom -eq 0 ]; then
+            echo "Warning, cannot set --extra-args with --cdrom"
+        else
+            cmdargs+=(--extra-args="$serial")
+        fi
     else
         if [ "${graphics,,}" == "vnc" ]; then
             cmdargs+=(--graphics "$vnc" --noautoconsole)
         fi
     fi
-
+    
     if [ $dryrun -gt 0 ]; then
         ( virt-install --connect $virt_uri ${cmdargs[@]} )
         rt=$?
@@ -522,7 +532,7 @@ status)
         exit 2
     fi
 
-    is_running $name
+    vm_is_running $name
     rt=$?
     ;;
 
@@ -547,7 +557,7 @@ setmem|setmaxmem)
     name="$args"
     live="--config"
 
-    if is_running $name; then
+    if vm_is_running $name; then
         if [[ $action =~ ^setmaxmem.*$ ]]; then
             echo "$PNAME error: VM must off or suspended to change Max Memory" >&2
             exit 1
@@ -574,7 +584,7 @@ setvcpu*)
     name="$args"
     live="--config"
 
-    if is_running $name; then
+    if vm_is_running $name; then
         live="--live"
     fi
 
@@ -594,7 +604,7 @@ stop|shutdown|destroy)
         exit 1
     fi
 
-    if is_running $name; then
+    if vm_is_running $name; then
         echo "$PNAME stopping '$name'.."
         if [ $dryrun -gt 0 ]; then
             ( $virsh destroy $name )
@@ -613,7 +623,7 @@ delete|undefine)
         exit 1
     fi
 
-    if is_running $name; then
+    if vm_is_running $name; then
         echo "$PNAME stopping '$name'.."
         if [ $dryrun -gt 0 ]; then
             ( $virsh destroy $name )
@@ -622,7 +632,7 @@ delete|undefine)
     fi
 
     if [ $dryrun -gt 0 ]; then
-        ( $virsh undefine $name )
+        ( $virsh undefine --nvram $name )
         rt=$?
     fi
     ;;
