sync output case

diff --git a/bin/kvmsh b/bin/kvmsh
--- a/bin/kvmsh
+++ b/bin/kvmsh
@@ -262,7 +262,7 @@ while [ $# -gt 0 ]; do
             if [[ "$format" == "qcow2" || "$format" == "raw" ]]; then
                 echo "$PNAME set disk typed as '$format'"
             else
-                echo "$PNAME Error, invalid format type '$format'"
+                echo "$PNAME error, invalid format type '$format'"
                 exit 1
             fi
             ;;
@@ -300,7 +300,7 @@ while [ $# -gt 0 ]; do
             disksz="$2"
             val=${disksz%%[!0-9]*}
             if (( $val < $mindisksz )); then
-                echo "$PNAME Error: Disk Size is less than minimum $mindisksz G" >&2
+                echo "$PNAME error: disk size is less than minimum $mindisksz G" >&2
                 exit 1
             fi
             shift
@@ -357,11 +357,11 @@ attach*)
     live="--config"
 
     if [ -z "$target" ]; then
-        echo "$PNAME Error determining pool storage directory: '$pool'" >&2
+        echo "$PNAME error determining pool storage directory: '$pool'" >&2
         exit 1
     fi
     if [ -z "$name" ]; then
-        echo "$PNAME Error, no VM defined."
+        echo "$PNAME error, no VM defined."
         exit 1
     fi
 
@@ -385,7 +385,7 @@ attach*)
 
         rt=$?
         if [ $rt -ne 0 ]; then
-            echo "$PNAME Error in create_disk() '$img'" >&2
+            echo "$PNAME error in create_disk() '$img'" >&2
             break
         fi
 
@@ -394,7 +394,7 @@ attach*)
 
             rt=$?
             if [ $rt -ne 0 ]; then
-                echo "$PNAME Error in attach-disk" >&2
+                echo "$PNAME error in attach-disk" >&2
                 break
             fi
         else
@@ -408,12 +408,12 @@ create)
     target="${poolmap[$pool]}"
 
     if [ -z "$target" ]; then
-        echo "$PNAME Error determining pool storage directory for '$pool'" >&2
+        echo "$PNAME error determining pool storage directory for '$pool'" >&2
         exit 1
     fi
 
     if [ -z "$name" ]; then
-        echo "$PNAME Error no vm name defined." >&2
+        echo "$PNAME error no vm name defined." >&2
         exit 1
     fi
 
@@ -424,7 +424,7 @@ create)
 
     rt=$?
     if [ $rt -ne 0 ]; then
-        echo "$PNAME Error in create_disk()" >&2
+        echo "$PNAME error in create_disk()" >&2
         exit $rt
     fi
 
@@ -480,12 +480,12 @@ clone)
     file="$path/$target-vda.img"
 
     if [ -z "$path" ]; then
-        echo "$PNAME Error determining storage path" >&2
+        echo "$PNAME error determining storage path" >&2
         exit 1
     fi
 
     if [ -z "$name" ] || [ -z "$target" ]; then
-        echo "$PNAME Error: no targets provided."
+        echo "$PNAME error: no targets provided."
         echo "$usage"
         exit 1
     fi
@@ -505,7 +505,7 @@ clone)
 # --- MAC-ADDRESS
 get-mac*|mac-addr*)
     if [ -z "$name" ]; then
-        echo "$PNAME Error: no target provided."
+        echo "$PNAME error: no target provided."
         echo "$usage"
         exit 1
     fi
@@ -537,7 +537,7 @@ start|suspend|restore|save|reset|resume|reboot|console|pool-info|info|dumpxml|de
 # --- SET MEMORY
 setmem|setmaxmem)
     if [ -z "$name" ] || [ -z "$args" ]; then
-        echo "$PNAME Error in arguments"
+        echo "$PNAME error in arguments"
         exit 1
     fi
     # flip args
@@ -547,7 +547,7 @@ setmem|setmaxmem)
 
     if is_running $name; then
         if [[ $action =~ ^setmaxmem.*$ ]]; then
-            echo "$PNAME Error: VM must off or suspended to change Max Memory" >&2
+            echo "$PNAME error: VM must off or suspended to change Max Memory" >&2
             exit 1
         fi
         live="--live"
@@ -564,7 +564,7 @@ setmem|setmaxmem)
 # --- SET VCPUS
 setvcpu*)
     if [ -z "$name" ] || [ -z "$args" ]; then
-        echo "$PNAME Error with setvcpus arguments"
+        echo "$PNAME error with setvcpus arguments"
         exit 1
     fi
     # flip args
@@ -588,7 +588,7 @@ setvcpu*)
 # --- STOP VMS
 stop|shutdown|destroy)
     if [ -z "$name" ]; then
-        echo "$PNAME Error: no <name> provided."
+        echo "$PNAME error: no <name> provided."
         exit 1
     fi
 
@@ -599,7 +599,7 @@ stop|shutdown|destroy)
             rt=$?
         fi
     else
-        echo "VM does not appear to be running.."
+        echo "$PNAME error, vm does not appear to be running.."
         rt=1
     fi
     ;;
@@ -607,7 +607,7 @@ stop|shutdown|destroy)
 # --- DELETE VMS
 delete|undefine)
     if [ -z "$name" ]; then
-        echo "$PNAME Error: no <name> provided."
+        echo "$PNAME error: no <name> provided."
         exit 1
     fi
 
@@ -638,7 +638,7 @@ vol-delete|delete-vol)
 # --- CREATE STORAGE POOL
 pool-create|create-pool)
     if [ -z "$name" ]; then
-        echo "$PNAME Error, directory name not provided."
+        echo "$PNAME error, directory name not provided."
         exit 1
     fi
 
@@ -685,7 +685,7 @@ pool-create|create-pool)
 # --- SET POOL AUTOSTART
 pool-autostart)
     if [ -z "$name" ]; then
-        echo "$PNAME Error, directory name not provided."
+        echo "$PNAME error, directory name not provided."
         exit 1
     fi
 
@@ -706,7 +706,7 @@ pool-start|start-pool)
         echo " -> Storage pool '$pool' already started.."
         rt=0
     else
-        echo "$PNAME Starting storage pool '$pool'.."
+        echo "$PNAME starting storage pool '$pool'.."
         if [ $dryrun -gt 0 ]; then
             ( $virsh pool-start $pool )
             rt=$?
@@ -721,7 +721,7 @@ pool-stop|stop-pool)
     fi
 
     if pool_is_active $pool; then
-        echo "$PNAME Stopping storage pool '$pool'"
+        echo "$PNAME stopping storage pool '$pool'"
         if [ $dryrun -gt 0 ]; then
             ( $virsh pool-destroy $pool )
             rt=$?
@@ -737,14 +737,14 @@ pool-delete|delete-pool)
     fi
 
     if pool_is_active $pool; then
-        echo "$PNAME Stopping storage pool '$pool'.."
+        echo "$PNAME stopping storage pool '$pool'.."
         if [ $dryrun -gt 0 ]; then
             ( $virsh pool-destroy $pool )
         fi
     fi
 
     if [ $dryrun -gt 0 ]; then
-        echo "$PNAME Deleting storage pool '$pool'.."
+        echo "$PNAME deleting storage pool '$pool'.."
         ( $virsh pool-undefine $pool )
         rt=$?
     fi
@@ -753,7 +753,7 @@ pool-delete|delete-pool)
 # -- LIST POOLS
 pool-list|list-pool*)
     if [ ${#poolmap[@]} -eq 0 ]; then
-        echo "$PNAME: No pools found or defined.."
+        echo "$PNAME no pools found or defined.."
         exit 0
     fi
 
@@ -786,7 +786,7 @@ vol-list|list-vol*)
     ;;
 
 *)
-    echo "$PNAME Action missing or not recognized."
+    echo "$PNAME action missing or not recognized."
     echo "$usage"
     ;;
 esac
