Tca 21.12 (#5)
* set groups default value
* error msg cleanup
* array is not multiline
* doc updates
* minor usage update

diff --git a/bin/kvmsh b/bin/kvmsh
--- a/bin/kvmsh
+++ b/bin/kvmsh
@@ -3,19 +3,18 @@
 #  kvmsh
 #
 #  Command-line tool for manipulating virtual machines wrapping the use
-#  of kvm tools 'virsh', 'virt-install', and 'virt-clone'.
+#  of kvm-qemu tools: 'virsh', 'virt-install', and 'virt-clone'.
 #
 #  Timothy C. Arland <tcarland@gmail.com, tarland@trace3.com>
 #
 PNAME=${0##*\/}
 AUTHOR="tcarland@gmail.com"
-VERSION="v21.05"
+VERSION="v21.12"
 
 # ------------------------------------
 # defaults
 ubuntu="ubuntu20.04"  # default os-var
 focal="ubuntu-20.04.1-legacy-server-amd64.iso"  # default image
-# alternate web installer
 #focal="http://us.archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/"
 
 pool="default"
@@ -92,6 +91,7 @@ Options:
 
 Actions: 
   create|delete  <name>  : Create or delete a VM (will not delete volumes).
+  define         <xml>   : Import or define a VM from the provided XML.
   start|stop     <name>  : Start or stop a VM. 
   create-pool <dir> <n>  : Creates a storage pool named <n> for a given dir.
   start-pool     <name>  : Activate an offline storage pool by name.
@@ -138,7 +138,7 @@ list_all_pools()
 vm_is_running()
 {
     local vm="$1"
-    state=$( $virsh list | grep $vm | awk '{ print $3 }' )
+    state=$($virsh list | grep $vm | awk '{ print $3 }')
     if [ "$state" == "running" ]; then
         return 0
     elif [ -z "$state" ]; then
@@ -153,7 +153,7 @@ pool_is_active()
     local vm="$1"
     local rt=1
 
-    state=$( $virsh pool-list --all | grep $vm | awk '{ print $2 }' )
+    state=$($virsh pool-list --all | grep $vm | awk '{ print $2 }')
 
     if [ "$state" == "active" ]; then
         rt=0
@@ -183,8 +183,8 @@ get_macaddr()
 {
     local target="$1"
 
-    xml=$( $virsh dumpxml $target 2>/dev/null )
-    mac=$( echo "$xml" | xmllint --xpath 'string(//interface/mac/@address)' - 2>/dev/null )
+    xml=$($virsh dumpxml $target 2>/dev/null)
+    mac=$(echo "$xml" | xmllint --xpath 'string(//interface/mac/@address)' - 2>/dev/null)
 
     echo "$mac"
 
@@ -198,7 +198,7 @@ get_pools()
     local pooldir=""
     local rt=0
 
-    names=$( $virsh pool-list --all --name 2>/dev/null )
+    names=$($virsh pool-list --all --name 2>/dev/null)
 
     for p in $names; do
         if [ -n "$p" ]; then
@@ -211,10 +211,10 @@ get_pools()
     fi
 
     for p in ${!pary[@]}; do
-        pooldir=$( $virsh pool-dumpxml $p 2>/dev/null | \
+        pooldir=$($virsh pool-dumpxml $p 2>/dev/null | \
           grep -A5 target | \
           grep path | \
-          sed -E 's/.*<path>(.*)<\/path>/\1/' )
+          sed -E 's/.*<path>(.*)<\/path>/\1/')
         if [ -d $pooldir ]; then
             pary[$p]="$pooldir"
         fi
@@ -228,11 +228,11 @@ get_num_drives()
 {
     local vmname="$1"
 
-    devs=$( $virsh dumpxml $vmname | \
+    devs=$($virsh dumpxml $vmname | \
       grep -A5 "<disk type='file' device='disk'>" | \
       grep "<target dev=" | \
       sed -E "s/^.*<target dev='(.*)' bus.*/\1/" | \
-      sed -E 's/vd(.)/\1/' )
+      sed -E 's/vd(.)/\1/')
 
     return ${#devs}
 }
@@ -422,7 +422,7 @@ create)
         osvar="$ubuntu"
     elif [ -z "$osvar" ]; then
         echo "$PNAME error: image provided but not os-variant, --osvar is required."
-        echo "  The tool 'osinfo-query os' will list os-variants."
+        echo "  The virsh tool 'osinfo-query os' will list os-variants."
         exit 1
     fi
 
@@ -443,13 +443,13 @@ create)
         exit $rt
     fi
 
-    cmdargs=(--name "$name" \
-      --memory $memory \
-      --vcpus $vcpus \
-      --os-type "$ostype" \
-      --os-variant "$osvar" \
-      --disk "path=$diskimg" \
-      --network "$network")
+    cmdargs=(--name "$name" 
+             --memory $memory 
+             --vcpus $vcpus 
+             --os-type "$ostype" 
+             --os-variant "$osvar" 
+             --disk "path=$diskimg" 
+             --network "$network")
 
     if [ $uefi -eq 0 ]; then
         cmdargs+=(--boot "uefi")
@@ -463,7 +463,7 @@ create)
     if [ $use_console -eq 0 ]; then
         cmdargs+=(--graphics "none")
         if [ $cdrom -eq 0 ]; then
-            echo "Warning, cannot set --extra-args with --cdrom"
+            echo "Warning, cannot set --extra-args with --cdrom" >&2
         else
             cmdargs+=(--extra-args="$serial")
         fi
@@ -497,7 +497,7 @@ clone)
     fi
 
     if [ -z "$name" ] || [ -z "$target" ]; then
-        echo "$PNAME error: no targets provided."
+        echo "$PNAME error: no targets provided." >&2
         echo "$usage"
         exit 1
     fi
@@ -517,7 +517,7 @@ clone)
 # --- MAC-ADDRESS
 get-mac*|mac-addr*)
     if [ -z "$name" ]; then
-        echo "$PNAME error: no target provided."
+        echo "$PNAME error: no target provided." >&2
         echo "$usage"
         exit 1
     fi
@@ -549,7 +549,7 @@ start|suspend|restore|save|reset|resume|reboot|console|pool-info|info|dumpxml|de
 # --- SET MEMORY
 setmem|setmaxmem)
     if [ -z "$name" ] || [ -z "$args" ]; then
-        echo "$PNAME error in arguments"
+        echo "$PNAME error in arguments" >&2
         exit 1
     fi
     # flip args
@@ -559,7 +559,7 @@ setmem|setmaxmem)
 
     if vm_is_running $name; then
         if [[ $action =~ ^setmaxmem.*$ ]]; then
-            echo "$PNAME error: VM must off or suspended to change Max Memory" >&2
+            echo "$PNAME Error, VM must off or suspended to change Max Memory" >&2
             exit 1
         fi
         live="--live"
@@ -576,7 +576,7 @@ setmem|setmaxmem)
 # --- SET VCPUS
 setvcpu*)
     if [ -z "$name" ] || [ -z "$args" ]; then
-        echo "$PNAME error with setvcpus arguments"
+        echo "$PNAME Error with 'setvcpus' arguments" >&2
         exit 1
     fi
     # flip args
@@ -600,7 +600,7 @@ setvcpu*)
 # --- STOP VMS
 stop|shutdown|destroy)
     if [ -z "$name" ]; then
-        echo "$PNAME error: no <name> provided."
+        echo "$PNAME Error, no <name> provided." >&2
         exit 1
     fi
 
@@ -611,7 +611,7 @@ stop|shutdown|destroy)
             rt=$?
         fi
     else
-        echo "$PNAME error, vm does not appear to be running.."
+        echo "$PNAME Error, vm does not appear to be running.." >&2
         rt=1
     fi
     ;;
@@ -619,12 +619,12 @@ stop|shutdown|destroy)
 # --- DELETE VMS
 delete|undefine)
     if [ -z "$name" ]; then
-        echo "$PNAME error: no <name> provided."
+        echo "$PNAME Error: no <name> provided." >&2
         exit 1
     fi
 
     if vm_is_running $name; then
-        echo "$PNAME stopping '$name'.."
+        echo " -> Stopping '$name'.."
         if [ $dryrun -gt 0 ]; then
             ( $virsh destroy $name )
             rt=$?
@@ -650,7 +650,7 @@ vol-delete|delete-vol)
 # --- CREATE STORAGE POOL
 pool-create|create-pool)
     if [ -z "$name" ]; then
-        echo "$PNAME error, directory name not provided."
+        echo "$PNAME Error, directory name not provided." >&2
         exit 1
     fi
 
@@ -665,7 +665,7 @@ pool-create|create-pool)
 
         rt=$?
         if [ $rt -gt 0 ]; then
-            echo "$PNAME Error in pool-define"
+            echo "$PNAME Error in pool-define" >&2
             exit $rt
         fi
         echo " -> Pool '$pool' defined."
@@ -683,7 +683,7 @@ pool-create|create-pool)
 
         rt=$?
         if [ $rt -gt 0 ]; then
-            echo "$PNAME Error starting pool"
+            echo "$PNAME Error starting pool" >&2
             exit $rt
         fi
         echo " -> Pool '$pool' started successfully."
@@ -697,7 +697,7 @@ pool-create|create-pool)
 # --- SET POOL AUTOSTART
 pool-autostart)
     if [ -z "$name" ]; then
-        echo "$PNAME error, directory name not provided."
+        echo "$PNAME error, directory name not provided." >&2
         exit 1
     fi
 
@@ -718,7 +718,7 @@ pool-start|start-pool)
         echo " -> Storage pool '$pool' already started.."
         rt=0
     else
-        echo "$PNAME starting storage pool '$pool'.."
+        echo " -> Starting storage pool '$pool'.."
         if [ $dryrun -gt 0 ]; then
             ( $virsh pool-start $pool )
             rt=$?
@@ -733,7 +733,7 @@ pool-stop|stop-pool)
     fi
 
     if pool_is_active $pool; then
-        echo "$PNAME stopping storage pool '$pool'"
+        echo " -> Stopping storage pool '$pool'"
         if [ $dryrun -gt 0 ]; then
             ( $virsh pool-destroy $pool )
             rt=$?
@@ -749,14 +749,14 @@ pool-delete|delete-pool)
     fi
 
     if pool_is_active $pool; then
-        echo "$PNAME stopping storage pool '$pool'.."
+        echo " -> Stopping storage pool '$pool'.."
         if [ $dryrun -gt 0 ]; then
             ( $virsh pool-destroy $pool )
         fi
     fi
 
     if [ $dryrun -gt 0 ]; then
-        echo "$PNAME deleting storage pool '$pool'.."
+        echo " -> Deleting storage pool '$pool'.."
         ( $virsh pool-undefine $pool )
         rt=$?
     fi
@@ -765,7 +765,7 @@ pool-delete|delete-pool)
 # -- LIST POOLS
 pool-list|list-pool*)
     if [ ${#poolmap[@]} -eq 0 ]; then
-        echo "$PNAME no pools found or defined.."
+        echo " -> no pools found or defined.." 
         exit 0
     fi
 
@@ -798,7 +798,7 @@ vol-list|list-vol*)
     ;;
 
 *)
-    echo "$PNAME action missing or not recognized."
+    echo "$PNAME action missing or not recognized." >&2
     echo "$usage"
     ;;
 esac
